name: 'Push Notification'

on: [push]

jobs:
  send_sms:
    runs-on: ubuntu-latest
    name: Send an SMS
    steps:
      - name: Sending SMS
        uses: twilio-labs/action-sms@master
        with:
          fromPhoneNumber: ${{ secrets.TWILIO_NUMBER }}
          toPhoneNumber: ${{ secrets.PERSONAL_NUMBER }}
          message: 'Ahoy from GitHub Actions'
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
